/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package richtercloud.reflection.form.builder.jpa;

import javax.swing.JSpinner;

/**
 *
 * @author richter
 */
public class IdPanel extends javax.swing.JPanel {
    private IdGenerator idGenerator;

    /**
     * Creates new form IdPanel
     */
    private IdPanel() {
        initComponents();
    }

    public IdPanel(IdGenerator idGenerator) {
        this();
        this.idGenerator = idGenerator;
    }

    public JSpinner getIdSpinner() {
        return idSpinner;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idSpinner = new javax.swing.JSpinner();
        nextIdButton = new javax.swing.JButton();

        nextIdButton.setText("Next id");
        nextIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextIdButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(idSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextIdButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(idSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(nextIdButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextIdButtonActionPerformed
        this.idSpinner.setValue(idGenerator.getNextId());
    }//GEN-LAST:event_nextIdButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner idSpinner;
    private javax.swing.JButton nextIdButton;
    // End of variables declaration//GEN-END:variables
}
