/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package richtercloud.reflection.form.builder.jpa;

import java.awt.FlowLayout;
import java.lang.reflect.Field;
import java.util.Map;
import javax.persistence.EntityManager;
import javax.swing.GroupLayout;
import javax.swing.JComponent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import richtercloud.reflection.form.builder.ReflectionFormPanel;
import richtercloud.reflection.form.builder.retriever.ValueRetriever;

/**
 *
 * @author richter
 * @param <E> a generic type for the entity class
 */
public class JPAReflectionFormPanel<E> extends ReflectionFormPanel<E> {
    private static final long serialVersionUID = 1L;
    private final static Logger LOGGER = LoggerFactory.getLogger(JPAReflectionFormPanel.class);
    private EntityManager entityManager;
    private ReflectionFormPanel<E> reflectionFormPanel;

    /**
     * Creates new form JPAReflectionFormPanel
     */
    public JPAReflectionFormPanel() {
        initComponents();
    }

    public JPAReflectionFormPanel(EntityManager entityManager, ReflectionFormPanel<E> reflectionFormPanel, Class<? extends E> entityClass, Map<Field, JComponent> fieldMapping, Map<Class<? extends JComponent>, ValueRetriever<?, ?>> valueRetrieverMapping) {
        super(fieldMapping, reflectionFormPanel.getInstance(), entityClass, valueRetrieverMapping);
        initComponents();
        this.entityManager = entityManager;
        this.reflectionFormPanel = reflectionFormPanel;
        GroupLayout reflectionFormPanelPanelLayout = new GroupLayout(this.reflectionFormPanelPanel);
        this.reflectionFormPanelPanel.setLayout(reflectionFormPanelPanelLayout);
        reflectionFormPanelPanelLayout.setHorizontalGroup(reflectionFormPanelPanelLayout.createSequentialGroup().addComponent(this.reflectionFormPanel));
        reflectionFormPanelPanelLayout.setVerticalGroup(reflectionFormPanelPanelLayout.createSequentialGroup().addComponent(this.reflectionFormPanel));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButton = new javax.swing.JButton();
        overviewButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        reflectionFormPanelPanel = new javax.swing.JPanel();

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        overviewButton.setText("Overview");

        statusLabel.setText(" ");

        javax.swing.GroupLayout reflectionFormPanelPanelLayout = new javax.swing.GroupLayout(reflectionFormPanelPanel);
        reflectionFormPanelPanel.setLayout(reflectionFormPanelPanelLayout);
        reflectionFormPanelPanelLayout.setHorizontalGroup(
            reflectionFormPanelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        reflectionFormPanelPanelLayout.setVerticalGroup(
            reflectionFormPanelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reflectionFormPanelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 242, Short.MAX_VALUE)
                        .addComponent(overviewButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveButton))
                    .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reflectionFormPanelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(overviewButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        Object instance;
        try {
            instance = this.reflectionFormPanel.retrieveInstance();
        } catch (IllegalArgumentException | IllegalAccessException ex) {
            LOGGER.debug(String.format("the following exception occured during persisting entity of type '%s'", this.reflectionFormPanel.getEntityClass()), ex);
            statusLabel.setText("An exception occured"); //@TODO:
            return;
        }
        entityManager.persist(instance);
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton overviewButton;
    private javax.swing.JPanel reflectionFormPanelPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
